### ISSUE TITLE
Small gumby exception

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#100]
```
2013-12-22 12:26:00+0100 [-] Killing leftover local sub processes...
Traceback (most recent call last):
  File "./gumby/run.py", line 93, in <module>
    _killGroup()
  File "./gumby/run.py", line 65, in _killGroup
    if getpgid(pid) == mypid and pid != mypid:
OSError: [Errno 3] No such process
```

**Comment by whirm** [comment]
Fixed in current master
