### ISSUE TITLE
Error when parsing utime

### ISSUE THREAD

**Issue by LipuFei** [Tribler/gumby#195]
```
Project root is: /home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel@2
NOT activating virtualenv.
Running graph_process_guard_data.sh
Parsing resource_usage file ./resource_usage.log
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel@2/gumby/scripts/extract_process_guard_stats.py", line 211, in <module>
    main(argv[1], argv[2])
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel@2/gumby/scripts/extract_process_guard_stats.py", line 199, in main
    parse_resource_files(input_directory, output_directory, start_time)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel@2/gumby/scripts/extract_process_guard_stats.py", line 108, in parse_resource_files
    utime = long(parts[14])
IndexError: list index out of range
```

**Comment by devos50** [comment]
Very old issue, never encountered this error during my experiments.
