### ISSUE TITLE
Running Dummy Profiler Yields Exception in twisted.defer

### ISSUE THREAD

**Issue by wouterjsmit** [Tribler/gumby#232]
I tried running various dummy profile configurations, but they all result in a similar looking exception.
Depending on the exact config, certain code in the ExperimentRunner fails, but the traceback points towards the twisted 'defer' module each time.

Trying to run a remote dummy config shows that the SSH is denied, giving a stacktrace to the same lines in twisted.defer as below.

Do you have any clue as to what might go wrong?
If you want, I can come by in the break at 15:30 quickly before my next lecture starts.

This is the error message for the local_prun_sync.conf

```
pathemeous@pathemeous-laptop:~/Documents/repos/gumbyFork$ gumby/run.py gumby/experiments/dummy/local_prun_sync.conf
INFO:ExperimentRunner:Syncing workspaces on remote head nodes...
INFO:ExperimentRunner:Great copying success!
INFO:ExperimentRunner:Running local and remote setup scripts
INFO:ExperimentRunner:Remote setup successful!
INFO:OneShotProcessProtocol:[] OUT: Project root is: /home/pathemeous/Documents/repos/gumbyFork
INFO:OneShotProcessProtocol:[] OUT: NOT activating virtualenv.
INFO:OneShotProcessProtocol:[] OUT: Running das4_setup.sh
INFO:OneShotProcessProtocol:[] ERR: ++ hostname
INFO:OneShotProcessProtocol:[] ERR: ++ grep '^fs[0-9]$'
INFO:OneShotProcessProtocol:[] ERR: + '[' '!' -z ']'
INFO:OneShotProcessProtocol:[] ERR: + quota -q
INFO:OneShotProcessProtocol:[] ERR: /home/pathemeous/Documents/repos/gumbyFork/gumby/scripts/das4_setup.sh: line 46: quota: command not found
INFO:OneShotProcessProtocol:[] ERR: + '[' 127 -ne 0 ']'
INFO:OneShotProcessProtocol:[] ERR: + echo 'Quota exceeded!'
INFO:OneShotProcessProtocol:[] ERR: + echo 'Aborting experiment.'
INFO:OneShotProcessProtocol:[] ERR: + exit 1
INFO:OneShotProcessProtocol:[] OUT: Quota exceeded!
INFO:OneShotProcessProtocol:[] OUT: Aborting experiment.
INFO:OneShotProcessProtocol:[das4_setup.sh] exit code 1
ERROR:ExperimentRunner:Experiment execution failed, exiting with error.
ERROR:ExperimentRunner:<twisted.python.failure.Failure <class 'twisted.internet.defer.FirstError'>>
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 416, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
    callable(*args, **kwargs)
exceptions.SystemExit: 1
INFO:root:Killing leftover local sub processes...
INFO:root:Done.
```

**Comment by whirm** [comment]
`INFO:OneShotProcessProtocol:[] ERR: /home/pathemeous/Documents/repos/gumbyFork/gumby/scripts/das4_setup.sh: line 46: quota: command not found`

You need to install the quota package:

`sudo apt install quota`

**Comment by whirm** [comment]
Closing this, reopen it if you still have issues.
