### ISSUE TITLE
Dispersy cannot start with Tribler experiment client

### ISSUE THREAD

**Issue by ardhipoetra** [Tribler/gumby#281]
In the latest `devel` branch. I found that if you called `start_session` in `TriblerDispersyExperimentScriptClient`, it will produce an assertion error. I guess it is because of commit 47f647cf153e90c66e007a70f310311999cf1b65.

You can test it by running hiddenservices experiment. Below is the log produced : 
```
ERROR   1478524088.08 TriblerDispersyClient:43    Starting Tribler Session
ERROR   1478524088.08 TriblerDispersyClient:101   Dispersy port set to 21002
ERROR   1478524088.12 TriblerDispersyClient:53    Upgrader
INFO    1478524088.80 tunnel_community:298   TunnelCommunity: setting become_exitnode = False
ERROR   1478524089.20 TriblerDispersyClient:48    Tribler Session started
Unhandled Error
Traceback (most recent call last):
  File "/home/ardhipoetra/git/thesis/gumby/experiments/dispersy/hiddenservices_client.py", line 244, in <module>
    main(HiddenServicesClient)
  File "/home/ardhipoetra/git/thesis/gumby/gumby/experiments/dispersyclient.py", line 516, in main
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 392, in callback
    assert not isinstance(result, Deferred)
exceptions.AssertionError:

ERROR   1478524089.21             log:143   Unhandled Error
Traceback (most recent call last):
  File "/home/ardhipoetra/git/thesis/gumby/experiments/dispersy/hiddenservices_client.py", line 244, in <module>
    main(HiddenServicesClient)
  File "/home/ardhipoetra/git/thesis/gumby/gumby/experiments/dispersyclient.py", line 516, in main
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 392, in callback
    assert not isinstance(result, Deferred)
exceptions.AssertionError:

ERROR   1478524091.05 hiddenservices_client:72    This peer is exit node: Yes
```

Note that I can run it in commit 89510a6ded8881eb8ec6657527cc10572cff6902

**Comment by devos50** [comment]
I'm pretty sure that this issue is invalid now that we did a complete refactor of the Gumby core.
