### ISSUE TITLE
AllChannel experiment stuck in trying-to-join-community

### ISSUE THREAD

**Issue by qstokkink** [Tribler/gumby#345]
The logs (`allchannel_small.conf`) reflect this (also an error on shutdown if `join()` never succeeds):
```
Starting #00003: launch_scenario.py
Found a logger.conf, using it.
WARNING 1514889600.70 launch_scenario:75    Unable to find scenario file: allchannel_small.scenario
INFO    1514889601.70             log:142   Starting factory <gumby.sync.ExperimentClientFactory instance at 0x7f294ae53d40>
WARNING 1514889601.70      experiment:76    Scenario file allchannel_small.scenario not found, attempting scenario file in experiment dir
INFO    1514889601.70      experiment:79    Scenario file found, using /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario
INFO    1514889602.03         backend:166   Loading Windows (alt)
INFO    1514889602.03         backend:166   Loading pyfs
INFO    1514889602.03         backend:166   Loading multi
INFO    1514889602.03         backend:166   Loading Google
INFO    1514889602.03         backend:166   Loading Gnome
INFO    1514889602.04         backend:166   Loading keyczar
INFO    1514889602.04         backend:166   Loading file
INFO    1514889602.32          driver:120   Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO    1514889602.34          driver:120   Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
INFO    1514889602.47 experiment_module:13    Load experiment module DispersyModule
INFO    1514889602.47 experiment_module:13    Load experiment module AllChannelModule
INFO    1514889602.47 base_dispersy_module:54    Dispersy port set to 12004
INFO    1514889602.50      experiment:177   Starting the experiment in 0.996237 secs.
INFO    1514889602.50            sync:356   The connection with the experiment server was lost with reason: Connection was closed cleanly.
INFO    1514889602.50             log:142   Stopping factory <gumby.sync.ExperimentClientFactory instance at 0x7f294ae53d40>
INFO    1514889603.50        scenario:288   Running scenario
INFO    1514889603.50        scenario:299   Register call 1514889603.5 /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario:4 isolate_community ['AllChannelCommunity'] {}
INFO    1514889603.50        scenario:299   Register call 1514889604.5 /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario:5 start_session [] {}
INFO    1514889603.50        scenario:299   Register call 1514889617.5 /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario:6 reset_dispersy_statistics [] {}
INFO    1514889603.50        scenario:299   Register call 1514889618.5 /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario:7 annotate ['start-experiment'] {}
INFO    1514889603.50        scenario:299   Register call 1514889623.5 /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario:9 join [] {}
INFO    1514889603.50        scenario:299   Register call 1514889653.5 /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario:15 stop_session [] {}
INFO    1514889603.50        scenario:299   Register call 1514889658.5 /home/quinten/tribler/gumby/experiments/dispersy/allchannel_small.scenario:16 stop [] {}
INFO    1514889603.50   gumby_session:38    Overriding CommunityLauncher AllChannelCommunity
INFO    1514889604.51 dispersy_module:32    Starting dispersy
INFO    1514889604.51        dispersy:1616  starting the Dispersy core...
INFO    1514889604.58        dispersy:284   update LAN address 10.0.2.15:0 -> 10.0.2.15:12004
INFO    1514889604.58        dispersy:291   update WAN address 0.0.0.0:0 -> 10.0.2.15:12004
INFO    1514889604.58        dispersy:1637  Dispersy core ready (database: /home/quinten/tribler/output/.DispersyModule-4492-4/sqlite/dispersy.db, port:12004)
CRITICAL 1514889604.58   gumby_session:96    LAUNCHING MarketCommunity for mid c85e508ddd660b14bcdeaa309a6edcf41ab9a8a0
INFO    1514889604.67       community:307   initializing:  MarketCommunity
INFO    1514889604.68 order_repository:135   Memory order repository used
INFO    1514889604.68 transaction_repository:134   Database transaction repository used
INFO    1514889604.68   order_manager:20    Market OrderManager initialized
INFO    1514889604.68 transaction_manager:20    Transaction Manager initialized
INFO    1514889604.68       community:168   Market community initialized with mid c85e508ddd660b14bcdeaa309a6edcf41ab9a8a0
CRITICAL 1514889604.68   gumby_session:96    LAUNCHING AllChannelCommunity for mid 4a49644ec18e917870e688afbe74a0bd22ef272f
INFO    1514889604.68       community:307   initializing:  AllChannelCommunity
CRITICAL 1514889604.74   gumby_session:96    LAUNCHING ChannelCommunity for mid 4a49644ec18e917870e688afbe74a0bd22ef272f
CRITICAL 1514889604.74   gumby_session:96    LAUNCHING PreviewChannelCommunity for mid 4a49644ec18e917870e688afbe74a0bd22ef272f
CRITICAL 1514889604.74   gumby_session:96    LAUNCHING DiscoveryCommunity for mid ad2d3a1ab78197fefca1cfc003f7c1d4c067bde0
INFO    1514889604.74       bootstrap:148   Resolving bootstrap addresses
INFO    1514889604.74       community:307   initializing:  DiscoveryCommunity
INFO    1514889604.75 dispersy_module:52    Finished starting dispersy
INFO    1514889604.75       bootstrap:154   Resolved quinten-VirtualBox into 127.0.1.1:30580
INFO    1514889604.75       bootstrap:154   Resolved quinten-VirtualBox into 127.0.1.1:30577
INFO    1514889604.75       bootstrap:154   Resolved quinten-VirtualBox into 127.0.1.1:30578
INFO    1514889604.75       bootstrap:154   Resolved quinten-VirtualBox into 127.0.1.1:30579
INFO    1514889610.70       community:364   Requesting crawl of node 18f4d35a:-1
INFO    1514889615.69       community:364   Requesting crawl of node 18f4d35a:-1
INFO    1514889620.70       community:364   Requesting crawl of node bae98f48:-1
INFO    1514889623.50 allchannel_module:85    trying-to-join-community
INFO    1514889624.51 allchannel_module:85    trying-to-join-community
INFO    1514889625.50 allchannel_module:85    trying-to-join-community
INFO    1514889625.69       community:364   Requesting crawl of node bae98f48:-1
INFO    1514889626.51 allchannel_module:85    trying-to-join-community
INFO    1514889627.50 allchannel_module:85    trying-to-join-community
INFO    1514889628.51 allchannel_module:85    trying-to-join-community
INFO    1514889629.51 allchannel_module:85    trying-to-join-community
INFO    1514889630.51 allchannel_module:85    trying-to-join-community
INFO    1514889630.69       community:364   Requesting crawl of node 892423cf:-1
INFO    1514889631.51 allchannel_module:85    trying-to-join-community
INFO    1514889632.50 allchannel_module:85    trying-to-join-community
INFO    1514889633.50 allchannel_module:85    trying-to-join-community
INFO    1514889634.50 allchannel_module:85    trying-to-join-community
INFO    1514889635.50 allchannel_module:85    trying-to-join-community
INFO    1514889635.69       community:364   Requesting crawl of node 892423cf:-1
INFO    1514889636.50 allchannel_module:85    trying-to-join-community
INFO    1514889637.50 allchannel_module:85    trying-to-join-community
INFO    1514889638.50 allchannel_module:85    trying-to-join-community
INFO    1514889639.50 allchannel_module:85    trying-to-join-community
INFO    1514889640.50 allchannel_module:85    trying-to-join-community
INFO    1514889640.69       community:364   Requesting crawl of node 18f4d35a:-1
INFO    1514889641.50 allchannel_module:85    trying-to-join-community
INFO    1514889642.50 allchannel_module:85    trying-to-join-community
INFO    1514889643.50 allchannel_module:85    trying-to-join-community
INFO    1514889644.50 allchannel_module:85    trying-to-join-community
INFO    1514889645.50 allchannel_module:85    trying-to-join-community
INFO    1514889645.69       community:364   Requesting crawl of node 18f4d35a:-1
INFO    1514889646.50 allchannel_module:85    trying-to-join-community
INFO    1514889647.50 allchannel_module:85    trying-to-join-community
INFO    1514889648.51 allchannel_module:85    trying-to-join-community
INFO    1514889649.51 allchannel_module:85    trying-to-join-community
INFO    1514889650.51 allchannel_module:85    trying-to-join-community
INFO    1514889650.69       community:364   Requesting crawl of node bae98f48:-1
INFO    1514889651.50 allchannel_module:85    trying-to-join-community
INFO    1514889652.50 allchannel_module:85    trying-to-join-community
INFO    1514889653.50        dispersy:1693  Stopping Dispersy Core..
INFO    1514889653.51        dispersy:1701  stopping the Dispersy core...
INFO    1514889653.71 allchannel_module:85    trying-to-join-community
ERROR   1514889653.71             log:142   Unhandled error in Deferred:
ERROR   1514889653.71             log:142   Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/quinten/tribler/gumby/experiments/dispersy/allchannel_module.py", line 87, in join
    cid = self.community._channelcast_db.getChannelIdFromDispersyCID(None)
exceptions.AttributeError: 'NoneType' object has no attribute '_channelcast_db'

INFO    1514889658.51      experiment:218   Stopping reactor
INFO    1514889658.52             log:142   Main loop terminated.
```

I added some debug info to the CommunityLoader: the AllChannelCommunity and ChannelCommunity seem to be properly loaded.

**Comment by qstokkink** [comment]
This is actually a bigger issue, as can also be seen in the logs: the `DiscoveryCommunity` uses a different mid for introduction. This means peers cannot find each other naturally (unless you call `introduce_peers` manually).
