### ISSUE TITLE
Not isInIOThread when shutting down Session

### ISSUE THREAD

**Issue by qstokkink** [Tribler/gumby#380]
```
2018-10-29 11:16:55,935:ERROR:Unhandled error in Deferred:

2018-10-29 11:16:55,936:ERROR:Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 503, in shutdown
    assert isInIOThread()
exceptions.AssertionError: 
```

**Comment by qstokkink** [comment]
...

https://github.com/Tribler/gumby/blob/9213270e4398eaf6bdc1362efbb2dfea63ec8191/gumby/modules/tribler_module.py#L67-L70

**Comment by qstokkink** [comment]
Fixed by changing the line to:

```python
reactor.callFromThread(self.session.shutdown)
```
