### ISSUE TITLE
Peer number not an int

### ISSUE THREAD

**Issue by qstokkink** [Tribler/gumby#381]
```
Traceback (most recent call last):
  File "gumby/experiments/ipv8/parse_ipv8_statistics.py", line 160, in <module>
    parser.run()
  File "gumby/experiments/ipv8/parse_ipv8_statistics.py", line 150, in run
    self.aggregate_messages()
  File "gumby/experiments/ipv8/parse_ipv8_statistics.py", line 20, in aggregate_messages
    for peer_nr, filename, dir in self.yield_files('ipv8_statistics.txt'):
  File "/home/quinten/Documents/gumby/gumby/statsparser.py", line 26, in yield_files
    peer_nr = int(peer)
ValueError: invalid literal for int() with base 10: '160771e8d5a839734844bdb6e0d5ff38a965a7f48b3c33b499ba0489318d'
```

**Comment by qstokkink** [comment]
Basically, having any subfolders in your monitor dir causes this.

Fixed by using try except:

```python
                                try:
                                    peer_nr = int(peer)

                                    filename = os.path.join(self.node_directory, headnode, node, peer, file_to_check)
                                    if os.path.exists(filename) and os.stat(filename).st_size > 0:
                                        yield peer_nr, filename, peerdir
                                except ValueError:
                                    break
```
