### ISSUE TITLE
Gumby is unable to load several communities

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#481]
For example, see [here](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_hidden_seeding/688/console):

```
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: 2021-02-24 08:57:11,883:ERROR:Future exception was never retrieved
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: future: <Future finished exception=KeyError('TriblerTunnelCommunity')>
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: Traceback (most recent call last):
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/home/pouwelse/python3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     result = self.fn(*self.args, **self.kwargs)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_hidden_seeding/gumby/gumby/experiment.py", line 113, in on_id_received
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     module.on_id_received()
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_hidden_seeding/gumby/experiments/tunnels/tunnel_module.py", line 68, in on_id_received
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     self.ipv8_community_launcher.community_kwargs["settings"] = TunnelSettings()
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_hidden_seeding/gumby/gumby/modules/community_experiment_module.py", line 78, in ipv8_community_launcher
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     return self.ipv8_community_loader.get_launcher(self.community_class.__name__)
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:   File "/var/scratch/pouwelse/jenkins2/workspace/validation_experiments/validation_experiment_hidden_seeding/tribler/src/pyipv8/ipv8/loader.py", line 442, in get_launcher
INFO:ProcessRunner:[das4_reserve_and_run...] OUT:     return self.community_launchers[name][0]
INFO:ProcessRunner:[das4_reserve_and_run...] OUT: KeyError: 'TriblerTunnelCommunity'
```

**Comment by qstokkink** [comment]
The loader structure was recently refactored. The launchers now need to be referred to by their launcher name instead of their community name.

**Comment by devos50** [comment]
Good to know, thanks! I will address that in another PR 👍
