### ISSUE TITLE
Unhandled Errors do not stop process

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#52]
While Dispersy quits due to having strict enabled, the gumby client does not when an exception occurs when calling a callback.

This needs to be fixed.
Example:

``` python:
2013-10-29 12:19:46+0100 [-] Unhandled Error
    Traceback (most recent call last):
      File "/var/scratch/emilon/jenkins/workspace/Experiment_PrivateSocial_gumby/gumby/experiments/dispersy/social_client.py", line 126, in <module>
        main(SocialClient)
      File "/var/scratch/emilon/jenkins/workspace/Experiment_PrivateSocial_gumby/gumby/gumby/experiments/dispersyclient.py", line 346, in main
        reactor.run()
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
        self.mainLoop()
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
        self.runUntilCurrent()
    --- <exception caught here> ---
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(*call.args, **call.kw)
```

Moreover, this exception is also not logged in the stderr, but in stdout similar to #50

**Comment by whirm** [comment]
Is Dispersy exiting with a !=0 status?

**Comment by NielsZeilemaker** [comment]
It's an internal gumby error which does not lead to quitting.

**Comment by whirm** [comment]
I just pushed a fix to master.

When dispersy quits due to having strict enabled, the client will schedule DispersyExperimentScriptCliet.stop() to be called.
