### ISSUE TITLE
Venv packages not compiled?

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#65]
I got this error:

``` python
2013-11-16 09:08:29+0100 [Uninitialized] Unhandled Error
    Traceback (most recent call last):
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
    --- <exception caught here> ---
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
        why = selectable.doWrite()
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 593, in doConnect
        self._connectDone()
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 607, in _connectDone
        self.protocol = self.connector.buildProtocol(self.getPeer())
      File "/home/emilon/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 1071, in buildProtocol
        return self.factory.buildProtocol(addr)
      File "/var/scratch/emilon/jenkins/workspace/Experiment_PrivateSocial/COMMUNITY_TYPE/poli/label/das4_vu/gumby/gumby/sync.py", line 289, in buildProtocol
        p = self.protocol(self.vars)
      File "/var/scratch/emilon/jenkins/workspace/Experiment_PrivateSocial/COMMUNITY_TYPE/poli/label/das4_vu/gumby/experiments/dispersy/social_client.py", line 55, in __init__
        from Tribler.community.privatesocial.community import PoliSocialCommunity
      File "/var/scratch/emilon/jenkins/workspace/Experiment_PrivateSocial/COMMUNITY_TYPE/poli/label/das4_vu/tribler/Tribler/community/privatesocial/community.py", line 4, in <module>
        from conversion import SocialConversion
      File "/var/scratch/emilon/jenkins/workspace/Experiment_PrivateSocial/COMMUNITY_TYPE/poli/label/das4_vu/tribler/Tribler/community/privatesocial/conversion.py", line 8, in <module>
        from Tribler.community.privatesemantic.rsa import get_bits
      File "/var/scratch/emilon/jenkins/workspace/Experiment_PrivateSocial/COMMUNITY_TYPE/poli/label/das4_vu/tribler/Tribler/community/privatesemantic/rsa.py", line 18, in <module>
        from numpy.oldnumeric.random_array import random
      File "/home/emilon/venv/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
        from . import add_newdocs
      File "/home/emilon/venv/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/home/emilon/venv/lib/python2.7/site-packages/numpy/lib/__init__.py", line 9, in <module>
        from .index_tricks import *
      File "/home/emilon/venv/lib/python2.7/site-packages/numpy/lib/index_tricks.py", line 19, in <module>
        from . import function_base
    exceptions.EOFError: EOF read where object expected
```

**Comment by whirm** [comment]
fixed on master
