### ISSUE TITLE
graph_process_guard_data.sh crashes on empty file

### ISSUE THREAD

**Issue by corpaul** [Tribler/gumby#85]
when resource_usage.log is empty:

Running gumby/scripts/graph_process_guard_data.sh
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR: Parsing resource_usage file src/resource_usage.log
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR: Traceback (most recent call last):
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:   File "/home/corpaul/workspace/gumby/scripts/extract_process_guard_stats.py", line 178, in <module>
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:     main(argv[1], argv[2])
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:   File "/home/corpaul/workspace/gumby/scripts/extract_process_guard_stats.py", line 166, in main
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:     parse_resource_files(input_directory, output_directory, start_time)
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:   File "/home/corpaul/workspace/gumby/scripts/extract_process_guard_stats.py", line 85, in parse_resource_files
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:     metainfo = json.loads(line)
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:   File "/home/corpaul/venv/inst/lib/python2.7/json/**init**.py", line 326, in loads
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:     return _default_decoder.decode(s)
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:   File "/home/corpaul/venv/inst/lib/python2.7/json/decoder.py", line 366, in decode
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:   File "/home/corpaul/venv/inst/lib/python2.7/json/decoder.py", line 384, in raw_decode
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR:     raise ValueError("No JSON object could be decoded")
2013-12-03 15:51:55+0100 [-] CMD "gumby/scripts/graph_process_guard_data.sh" ERR: ValueError: No JSON object could be decoded

**Comment by whirm** [comment]
@corpaul: do you want to add a check for it?

**Comment by corpaul** [comment]
https://github.com/Tribler/gumby/pull/86

**Comment by whirm** [comment]
@corpaul you can close it if it's fixed
